name: Build and Deploy (Staging)

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout and build
        run: |
          npm install
          npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Push to S3
        run: |
          aws s3 sync out/ s3://battlefly-dashboards-staging --delete
          aws cloudfront create-invalidation --distribution-id E2IXO0IUIGAFSM --paths "/*"
